// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ALS_BillingAppointmentAPI.DB
{
    public partial class TbMHolidays
    {
        public int HolidaysId { get; set; }
        public DateTime? HolidaysDate { get; set; }
        public string HolidaysDays { get; set; }
        public string Comment { get; set; }
    }
}